// Code generated by hertz generator.

package v1

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	v1 "github.com/tpl-x/hertz/biz/model/api/v1"
)

// SayHello .
// @router /api/v1/hello [GET]
func SayHello(ctx context.Context, c *app.RequestContext) {
	var err error
	var req v1.HelloRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(v1.HelloResponse)

	c.JSON(consts.StatusOK, resp)
}
